package net.noscape.project.supremetags.enums;

public enum EditingType {

    CHANGING_TAG(),
    CHANGING_PERMISSION(),
    CHANGING_CATEGORY(),
    CHANGING_DESCRIPTION(),
    CHANGING_COST(),
    CHANGING_DISPLAY_ITEM(),
    CHANGING_ORDER(),
    CHANGING_RARITY(),
    CHANGING_DISPLAYNAME(),
    CHANGING_MATERIAL(),
    CHANGING_SLOT(),
    CHANGING_PERMISSION_SEE_CATEGORY(),
    CHANGING_COST_CATEGORY(),
    CHANGING_GLOW();
}