package net.noscape.project.supremetags.enums;

public enum EditingType {

    CHANGING_TAG(),
    CHANGING_PERMISSION(),
    CHANGING_CATEGORY(),
    CHANGING_DESCRIPTION(),
    CHANGING_COST(),
    CHANGING_ECONOMY_TYPE(),
    CHANGING_ECONOMY_TAKE_CMD(),
    CHANGING_ECONOMY_CONDITION(),
    CHANGING_DISPLAY_ITEM(),
    CHANGING_ORDER(),
    CHANGING_RARITY(),
    CHANGING_DISPLAYNAME(),
    CHANGING_MATERIAL(),
    CHANGING_VOUCHER_DISPLAYNAME(),
    CHANGING_VOUCHER_MATERIAL(),
    CHANGING_VOUCHER_LORE(),
    ADDING_VOUCHER_LORE_LINE(),
    CHANGING_VOUCHER_LORE_LINE(),
    CHANGING_VOUCHER_MODEL_DATA(),
    CHANGING_SLOT(),
    CHANGING_PERMISSION_SEE_CATEGORY(),
    CHANGING_COST_CATEGORY(),
    CHANGING_GLOW();
}
